spring: 
  application: 
    name: basicboot
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@teacherdev09.kro.kr:8877:xe
    username: spring
    password: spring
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views
mybatis: 
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**/*.xml
server: 
  port: 9090
  servlet: 
    encoding: 
      charset: UTF-8